# Generated by Django 4.0.6 on 2022-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='expiry_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='fine',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
