# Generated by Django 4.0.6 on 2022-07-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_issuedbook_expiry_date_alter_issuedbook_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Your sex', max_length=10),
        ),
    ]
