# Generated by Django 4.0.6 on 2022-07-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_alter_student_reg_no_alter_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
