# Generated by Django 4.0.6 on 2022-07-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_student_username'),
        ('bookstore', '0005_alter_student_username'),
    ]

    operations = [
    ]
